apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-pv
spec:
  selector:
    matchLabels:
      app: mysql-pv
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-pv
    spec:
      containers:
      - name: mysql-pv
        image: us-central1-docker.pkg.dev/my-online-market-388401/hello-repo/my-online-market-mysql:1.1
        env:
          # 在实际中使用 secret
        - name: MYSQL_ROOT_PASSWORD
          value: kurumi9452
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: pvc-demo-vol
          mountPath: /var/lib/mysql
        - name: pvc-demo-vol
          mountPath: /var/log/mysql
        - name: pvc-demo-vol
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: pvc-demo-vol
        persistentVolumeClaim:
          claimName: pvc-demo